name: Unit tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4'
    
    - name: Download dependencies
      run: go mod download
    
    - name: Run tests with coverage
      run: |
        TEST_OUTPUT=$(go test -cover ./...)
        echo "test-results<<EOF" >> $GITHUB_OUTPUT
        echo "$TEST_OUTPUT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT